name: "ZITADEL e2e Tests"

on:
  workflow_call:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        browser: [firefox, chrome]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@v3
      -
        uses: actions/download-artifact@v3
        with:
          path: .artifacts
          name: zitadel-linux-amd64
      -
        name: Unpack executable
        run: |
          tar -xvf .artifacts/zitadel-linux-amd64.tar
          mv zitadel-linux-amd64/zitadel ./zitadel
      -
        name: Start DB and ZITADEL
        run: |
          mv ./build/docker-compose-e2e.yaml ./docker-compose.yaml
          docker compose up --detach --wait
      - 
        name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_BASE_URL: http://localhost:8080/ui/console
          CYPRESS_WEBHOOK_HANDLER_HOST: host.docker.internal
          CYPRESS_DATABASE_CONNECTION_URL: 'postgresql://zitadel@localhost:5432/zitadel'
          CYPRESS_BACKEND_URL: http://localhost:8080
        with:
          working-directory: e2e
          browser: ${{ matrix.browser }}
          command: npm run e2e
          config-file: cypress.config.ts
      - 
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: production-tests-${{ matrix.browser }}
          path: |
            e2e/cypress/screenshots
            e2e/cypress/videos
            e2e/cypress/results
          retention-days: 30
